### ISSUE TITLE
Distinguish between bicycle pump and repair station

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#10]
Specify if a just is a pump at a location for `amenity=bicycle_repair_station`. Can it get a dedicated icon? That also can be mixed with when there are both services at one location. [Relevant tags in OSM](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_repair_station):

- General for both: `amenity=bicycle_repair_station`
- `service:bicycle:pump=yes`
- `service:bicycle:tools=no`

**Comment by Beck-berry** [comment]
Could you please name them for the legend?
