### ISSUE TITLE
Bikely: Broken API both in new locations and available lockers

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#100]
There are now new locations with Bikely bike lockers in Drammen. See screenshot from app. Any reason that:

1. New locations are not updated?
2. Number of lockers on existing locations are not the same? (Screenshots taken at the same time.)

Sykkelveier.no:
![image](https://github.com/buskerudbyen/cycling-norway/assets/70061303/b04570a6-d627-4280-b38b-3a17969c2af9)
Bikely app:
![image](https://github.com/buskerudbyen/cycling-norway/assets/70061303/af2da39c-3543-4c52-8ab6-22bb2a13b1b8)

**Comment by leonardehrenfried** [comment]
I took a look at this today.

My previous API call https://api.safebikely.com/api/v1/s/locations is no longer working and return an error 404.

I've looked the Bikely website and cannot find any technical information about how to consume the API. Do you have any?

**Comment by tsobuskerudbyen** [comment]
Answer from Bikely just now:

> Fra: Keivan Farr
> Sendt: fredag 23. februar 2024 09:43
> Til: Trond Solem 
> Kopi: Hallvar Bergh; Leonard
> Emne: Re: [buskerudbyen/cycling-norway] Bikley: Broken API both in new locations and available lockers
> 
> Hello Trond, 
>
> Sorry for the late reply on this one. We removed part of the API for external clients and this endpoint was one of them.
> 
> As a temporary alternative you can use our public (no API key) end point.
> Here is our full documentation [https://api.safebikely.com/swagger/index.html](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapi.safebikely.com%2Fswagger%2Findex.html&data=05%7C02%7CTrond.Solem%40buskerudbyen.no%7C3b526dc7f2964cfe260908dc344b88d1%7Cf602a20a3d6c4584a01472a3939f57fe%7C0%7C0%7C638442746224823143%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=e41L88ILJ3u8zkoOPInQ3%2BAQvYr%2FheeI5owJU%2B6%2B0zw%3D&reserved=0) for Leonard. 
>
>What you need is the "/api/services/app/Location/GetPins" endpoint, return type is the same as before. You can find all the details from the Swagger page. I hope this fixes the issue for now, until we find a better solution. 
>
>Regards,

**Comment by tsobuskerudbyen** [comment]
Is this then dependent on https://github.com/opentripplanner/OpenTripPlanner/pull/5708 ?
