### ISSUE TITLE
Small screen text box UX issue: "Fra" and "Til" disappears on first try

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#105]
Tested on two Android mobile phones, running Firefox and Chrome. (Not a problem on iPads as the button "Tekstsøk" is not needed.)
Please see video here: https://drive.google.com/file/d/1KvCs5a2MaWXkcUq0heGFg0DXo3OPkXR3/view?usp=sharing

It is replicable every time. I can reload the page and the same thing happens again. Not reloading and clicking the Tekstsøk button again makes the to and from fields work just fine.

**Comment by Beck-berry** [comment]
Deployed now.
