### ISSUE TITLE
Bikely: The icon disappears after zoom levels 11 and up (zooming down) in Drammen city center 

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#107]
Tested on Chrome and Edge om Windows. Same issue. Seems to be a bit on and off. Can you please check if you can reproduce @Beck-berry ?

![image](https://github.com/buskerudbyen/cycling-norway/assets/70061303/bd6671e1-048d-4e0d-b755-721851a74572)

**Comment by leonardehrenfried** [comment]
![image](https://github.com/buskerudbyen/cycling-norway/assets/151346/9cc942f3-817e-45c4-a0ee-19b75c5af2be)

I can reproduce it in Chrome. Weirdly it works in Firefox, which is unusual because there stuff usually breaks.

@Beck-berry Can you take a look?

**Comment by Beck-berry** [comment]
For me, they are visible both on Firefox and Chromium 9-22 zoom levels. (I use Linux Mint 20.3 Una - Ubuntu). Also on mobile (Android, Chrome).
I'll check this another time and on other environments too.

**Comment by Beck-berry** [comment]
On Windows 10, Chrome, the icon visible at 9-16 zoom levels, then disappears.

**Comment by tsobuskerudbyen** [comment]
Strange stuff! Can something be done about it?

**Comment by Beck-berry** [comment]
I notoriously refreshed the site both on Chromium and Firefox, dropped the cache multiple times, and it seemed to solve the problem, however the browsers would never show the same result. (Same icons at the same places on the same zoom levels.)
I also downloaded the Bikely App to check the locations and there should be more than it is visible.
I think something's up with the backend, some pbfs from byvekstavtale.leonard.io/vectortiles/bikely are not *always* available and I believe that this causes the icons to appear and disappear almost randomly. @leonardehrenfried could you check this issue?

**Comment by leonardehrenfried** [comment]
I'm investigating this right now and I can confirm that it's because of the backend but I haven't actually figured out what exactly the problem is.

**Comment by leonardehrenfried** [comment]
I think I isolated the problem and it was unfortunately deep inside the guts of OTP. I've deployed a fix and will monitor the situation.

Would be great if you could provide a bit of feedback if you feel like the situation has improved.

**Comment by leonardehrenfried** [comment]
I don't experience any strange problems anymore so I believe that my fix was correct.

@Beck-berry @tsobuskerudbyen If you see this problem coming back, please re-open.

**Comment by Beck-berry** [comment]
I can confirm: seems to be OK on Chromium and Firefox.
