### ISSUE TITLE
Button: "Nullstill rute" does not clear the from [Fra] and to [Till] fields

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#108]
1. Add a random to and from location, and find the route.
2. Click "Nullstill rute" and see that the fields are still filled with text. They should be cleared.

**Comment by Beck-berry** [comment]
I had my struggles with this...

Infos that helped:
* [Stackoverflow conversation](https://stackoverflow.com/questions/59790956/material-ui-autocomplete-clear-value)
* [MUI github issue](https://github.com/mui/material-ui/issues/4736)

**Comment by tsobuskerudbyen** [comment]
Nice digging for info here! :) Good work.
