### ISSUE TITLE
Cycle routes should have the same colour on all zoom leveles

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#109]
Can we change the colour on local cycle routes on all zoom levels to the same light green. Also, when zooming out to the higher overview levels. Now, the colour changes aroun zoom level 10, to the same colour as cycle infrastructure on lower zoom levels. This can be confusing.

**Comment by Beck-berry** [comment]
Just to be clear, @tsobuskerudbyen, do you mean this transition?

Zoom level < 10:
![Image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/c1a7a52a-391e-45ac-8d16-5ac8ddadbd26)

Zoom level >= 10:
![Image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/928569e9-176d-4f4e-a5ec-194235a9d45e)

It's not the colour changing but the bike layer appearing at zoom level 10. I can make it visible below that, too.

**Comment by tsobuskerudbyen** [comment]
Sorry, no. My bad. This is what I mean:

![image](https://github.com/buskerudbyen/cycling-norway/assets/70061303/96ccd748-0563-4772-a55c-f7e44a28c5df)

**Comment by Beck-berry** [comment]
Okay, I get it! It happens at zoom level 14, and you're right, there were two different colours used.

Zoom < 14:
![Image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/26e4575b-383e-46b6-8605-28accfaf3335)

Zoom >= 14:
![Image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/edaada7a-b29d-41b5-87f6-3557950c9e24)

You like it this way?

**Comment by tsobuskerudbyen** [comment]
Nice. Like that you then see the national routes best. Go for it. Thanks!
