### ISSUE TITLE
Mutch work getting more cycle shops visible?

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#110]
Can the likes of this:
https://www.openstreetmap.org/node/6044914054
And this:
https://www.openstreetmap.org/node/1271211577
With:
`service:bicycle=sales`, or `service:bicycle:retail=yes` or `service:bicycle:second_hand=yes`
Be shown with bicycle shop symbol? Can we traverse over all shops? Or too much work?

**Comment by leonardehrenfried** [comment]
It's not a lot of work and @Beck-berry can do it.
