### ISSUE TITLE
Rephrase "Bikely parkering" to something more generic

### ISSUE THREAD

**Issue by leonardehrenfried** [buskerudbyen/cycling-norway#120]
I've added Bikeep realtime parking information today however, the legend still talks about "Bikely parkering".

![image](https://github.com/buskerudbyen/cycling-norway/assets/151346/292e3c90-1c26-4806-876e-a3764108324b)

@tsobuskerudbyen Can you come up with a more generic label?

**Comment by tsobuskerudbyen** [comment]
Documented here. https://github.com/buskerudbyen/cycling-norway/issues/102#issuecomment-2015081492 

We need to discuss the number of items in the legend later. For now Bikeep should be seprate from Bikely.

**Comment by tsobuskerudbyen** [comment]
@leonardehrenfried: Can you look at this one or assign to Beck-berry?

**Comment by leonardehrenfried** [comment]
@Beck-berry can you please take care of it?

**Comment by Beck-berry** [comment]
We can create a switch in the legend for separate layers only.
Since @tsobuskerudbyen wants Bikeep and Bikely to be separate, is there a way to add them as seperate layers, @leonardehrenfried? Do I understand right, you added the Bikeep data to the `byvekstavtale.leonard.io/tiles/bikely.json` file? Shouldn't be there a `bikeep.json`? That way I could add a different icon and switch to the legend.

**Comment by leonardehrenfried** [comment]
@Beck-berry here are the two tilejson files:

- https://bikely.cycling-norway.leonard.io/otp/routers/default/vectorTiles/parking/tilejson.json
- https://bikeep.cycling-norway.leonard.io/otp/routers/default/vectorTiles/parking/tilejson.json

**Comment by Beck-berry** [comment]
@leonardehrenfried I changed the bikely source and added the bikeep layer (you can check the connected commit) but somehow they do not appear, however both requests got an OK response. Do you have an idea what's wrong? I'll keep investigating on this otherwise.

**Comment by leonardehrenfried** [comment]
I think I know what the problem is and I'm taking a look today.

**Comment by leonardehrenfried** [comment]
I have now fixed both the backend and the frontend and Bikeep and Bikely show up as different layers.

In Sandvika you can see both on the same screen: https://sykkelveier.no/?layers=anlegg%2Crute-nb%2Crute-lb%2Crute-no%2Crute-lo%2Cpoffentlig%2Cpprivat%2Cpskap%2Cphotell%2Cptak%2Crep%2Cbr%C3%B8yting-ok%2Cbr%C3%B8yting-senere%2Csn%C3%B8r%2Cpumpe%2Cbutikk%2Cpumptrack%2Cloype%2Cbikely%2Cbikeep%2Clavhastighet#13.36/59.89325/10.53658

I would suggest to close this ticket and @tsobuskerudbyen and @Beck-berry can work on the fine-tuning of the look and feel over at #102.
