### ISSUE TITLE
State bugs in legend

### ISSUE THREAD

**Issue by michaeljohansen** [buskerudbyen/cycling-norway#124]
There are two state bugs in the legend:
1. Legend does not load items until after first zooming, so it is empty on load
2. Disabling and re-enabling an item in the legend makes the item disappear

**Comment by Beck-berry** [comment]
Updating the [legend plugin](https://www.npmjs.com/package/@watergis/maplibre-gl-legend/v/2.0.5) to the latest version (2.0.5) seems to solve the problem.
