### ISSUE TITLE
Height information on the route - Multiple issues

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#125]
Interesting this one. Seem like the bridge is missing completely in the height information, and – also – the data on the road under the bridge seems to make the route jump up and down. Sill the total for the selected route is only 0.17 meters. So, this is many problems in one:

1. If my statement over true. If yes, then we need to investigate how the height is calculated (simlar to #78). If the bridge vanishes in thin air for the calculation, we need to document this and show this to the user in some way. Text under that says something like: "Bridges makes it all wrong". :) Norwegian: "Kalkuleringen tar ikke høyde for broer. Dette er data vi jobber med å få inn." 
– Also, make a ticket for this in OTP in that if the route includes a bridge it needs to be improved. (And perhaps documentation for it.)
2. We want to show the total of meters going up for the route. Now it seems to calculate: Hills going up - down = result. It should say just total going up.
3. Also, in Norway the decimal divider is a comma. (Yes, we are a strange kind.) So, just round it up to nearest meter.

![image](https://github.com/buskerudbyen/cycling-norway/assets/70061303/d1f64bb7-e19c-4f61-93af-ca6b00f8308d)

Route: https://sykkelveier.no/?from=59.74375%2C10.23235&to=59.74759%2C10.23945
G.S.V: https://maps.app.goo.gl/sbvw9UKDRhAWw9zr5 (showing the bridge in question)
The same bridge in OSM: https://www.openstreetmap.org/way/112396089
https://otp2debug.entur.org/ with elevation turned on:

![image](https://github.com/buskerudbyen/cycling-norway/assets/70061303/f55d8510-fa7a-4c31-adb9-7aa9cc519110)

**Comment by Beck-berry** [comment]
> We want to show the total of meters going up for the route. Now it seems to calculate: Hills going up - down = result.

The elevation number, that is shown now, is the height difference of the destination and the start. So basically do you want to display the difference between the highest point and the start?

---

I changed the numbering of the labels and added the note for now:

![Image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/d50d280d-0fb1-460f-acd9-2fe71413f593)

**Comment by tsobuskerudbyen** [comment]
When cycling I would prefer to know the total amount of meters going up. So, if I have to climb two or more hills on a route, the total meters going up should be calculated.
