### ISSUE TITLE
Widget: URL on frontpage on widget.sykkelveier.no gives 404

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#131]
Please correct the URL on this page https://widget.sykkelveier.no/ :
> Dette er en enkel demoside for Sykkelveier.no-widgeten. Du kan bruke widgeten uten forhåndssamtykke. Se vår kildekode for instruksjoner om hvordan du bruker widgeten på ditt eget nettsted: https://github.com/buskerudbyen/cycling-norway/widget

Also, the instructions [NO: instruksjoner] is under on the same page. So, does a new url give any new information here? Can the text be revised? Suggestion:

> Destinasjonskart som kan legges inn på egen nettside: Dette er en widget som fremhever bruk av sykkel/elsparkesykkel til lokasjoner i Norge. Løsningen benytter seg av stedssøk fra Entur og sykkelløsninger fra mange andre kilder, men først og fremst OpenStreetMap og fra løsningen [sykkelveier.no](https://sykkelveier.no/) Man kan bruke widgeten på egen webside uten forhåndssamtykke. Se under for instruksjoner om hvordan den kan benyttes.

**Comment by leonardehrenfried** [comment]
I've updated the text on https://widget.sykkelveier.no/

![image](https://github.com/buskerudbyen/cycling-norway/assets/151346/af9f5245-5e3d-4df5-ab3b-a2da79e60ef8)

Can you check that I got it correct and close the ticket?

**Comment by tsobuskerudbyen** [comment]
Looks good. Thanks!
