### ISSUE TITLE
Widget: No cycle routes show up - Always error

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#133]
How to reproduce:
1. Find a desitnation.
2. Find a starting point close by.
3. You always get the an error.

![image](https://github.com/buskerudbyen/cycling-norway/assets/70061303/dff830a2-fbcc-4737-af10-065166a69592)

**Comment by leonardehrenfried** [comment]
This is again because of the lat/lon being swapped.

![image](https://github.com/buskerudbyen/cycling-norway/assets/151346/547c6c20-6c11-4c2f-bfec-84d8492f9654)


@Beck-berry can you please take care of this.

**Comment by leonardehrenfried** [comment]
@Beck-berry I saw that you started to work on this over here https://github.com/buskerudbyen/cycling-norway/commit/f48b539cb354cb19cf17dfaeef1df64029be9694

Is this ready to merge and roll out>?

**Comment by Beck-berry** [comment]
@leonardehrenfried Yes. I raised a PR. (Initially I wanted to fix all widget errors together.)

**Comment by leonardehrenfried** [comment]
![image](https://github.com/buskerudbyen/cycling-norway/assets/151346/a0113e57-22b5-45be-b288-73e099b0ae1e)

@tsobuskerudbyen This problem should now be fixed. Can you test again?
