### ISSUE TITLE
Add legend/explanation for snow plowing colours

### ISSUE THREAD

**Issue by leonardehrenfried** [buskerudbyen/cycling-norway#14]
Please check if it's possible to add items to the legend about what the snow plowing colours mean.

- green: plowed less than 3 hours ago
- red: plowed more than 3 hours ago

**Comment by tsobuskerudbyen** [comment]
Can this be added on the legend [Tegnforklaring], and then only be visible when Konnerudgata is in the area the user is browsing? Or will it be on a separate window? If the latter, how can we remove it or make it invisible for users that are not interested in the snow ploughing information?

> Norwegian tekst:
> Brøyting om vinteren (test)
> [green thick line] - 0-3 timer siden sist brøyting
> [yellow thick line] - 3 timer eller senere
> 
> Dette kartet er en pilot utarbeidet av Viken fylkeskommune, Statens vegvesen, Drammen kommune og Buskerudbyen i 2023.

**Comment by Beck-berry** [comment]
We can add these to the legend and so they are easy to turn on and off:
![Képernyőkép_2023-03-11_14-11-18](https://user-images.githubusercontent.com/46535522/224486580-a228ede6-6889-41e8-966d-aaa33b68c24c.png)
![Képernyőkép_2023-03-11_14-11-41](https://user-images.githubusercontent.com/46535522/224486581-eaa4af58-fb02-4ad1-a27c-814c26b6fbd5.png)

@tsobuskerudbyen But it is not possible to add additional text there. If you'd like to have an explanation / description, we can create a separate window on the side for that. (That could be closeable so it is only visible on the first visit, until the user closes it.)

**Comment by leonardehrenfried** [comment]
Could we add more text when clicking on the line?

**Comment by tsobuskerudbyen** [comment]
Great that you added the tick box to the legend. Looks good. It would be best to have a possibility to default not show any of the snow ploughing information. This is just a test/pilot, and for six months of the year the data is not relevant at all and – hence – just cluttering up the user interface. Even now the live/actual data we get in is unreliable. Can this be solved in some way? E.g.:

1. Add another tag to the url? Like the simulation? [?simulateSnowPlows#14/59.739/10.1878](https://leonard.io/cycling-norway/?simulateSnowPlows#14/59.739/10.1878). Like `?SnowPlows`
1. The one solution that I guess involves the most work is to set up a duplicate instance of the whole https://leonard.io/cycling-norway/ solution. 
...But, I do not know what is possible with the technology and tools you are working with now.

**Comment by tsobuskerudbyen** [comment]
Also note: We do not want a red line. Only green and yellow.

**Comment by Beck-berry** [comment]
@leonardehrenfried Do you think of the popup? We can add any text there.

![Képernyőkép_2023-03-15_15-30-04](https://user-images.githubusercontent.com/46535522/225341073-18c70cef-b62e-4629-a6c0-71e4d4a0418d.png)

**Comment by leonardehrenfried** [comment]
This is a good solution.

**Comment by Beck-berry** [comment]
@tsobuskerudbyen Could you give us a proper translation to the text in the popup?

**Comment by tsobuskerudbyen** [comment]
Orange colour is fine. Good suggestion. Norwegian tekst:

> **Vinterbrøytning av sykkelveier (test)**
> [green thick line] - 0-3 timer siden sist brøyting
> [orange thick line] - 3 timer eller senere
>
> Vinterdriftsinformasjon i sykkelkartet er en pilot i prosjektet: «Smart Drift», i samarbeid mellom Statens vegvesen, Viken fylkeskommune, Drammen kommune og Buskerudbyen i 2023. Har du spørsmål, ta kontakt med post(krøllalfa)buskerudbyen(punktum)no.
