### ISSUE TITLE
More base map details: Bike shops and stadiums

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#17]
Some more details should be added to the base map: 
Sports stadiums - Like: https://www.openstreetmap.org/#map=18/59.73440/10.20162&layers=C 
Bike shops - Like: https://www.openstreetmap.org/#map=20/59.73817/10.20178&layers=C

**Comment by Beck-berry** [comment]
Could you please name them for the legend?

**Comment by tsobuskerudbyen** [comment]
Thinking more on this. 

1. Sports stadiums are okay to not add to the legend. All of them are possible POIs and some of them are named, and - hence - it is more general part of the map. But, from https://github.com/buskerudbyen/proposal-visualizer/pull/2 it seems that `leisure=stadium` is added. Can we alo add `building=sports_centre`, `leisure=pitch`, and the combination: `leisure=track` and `sport=athletics`?
2. Bike shops - Norwegian, for legend: "Sykkelbutikk" - Is this includning `shop=sports` that has some sort of `service:bicycle:*=yes`? If not, can it be added?

Can the latter be added to some documentation? Can also do this myself - in the traning documentation, but you must implement it first. :)

**Comment by Beck-berry** [comment]
What kind of documentation are you thinking of? Like the README file of the repository? Or a Wiki here in GitHub?

**Comment by Beck-berry** [comment]
These three ("building=sports_centre, leisure=pitch, and the combination: leisure=track and sport=athletics") should be handled the same way? Same icon?

If not, shouldn't we make any constraints to the `leisure=pitch`? It can be anything from soccer to chess... (I'm looking for a suitable icon.)

**Comment by tsobuskerudbyen** [comment]
Not sure you neeed an icon for all this. It may be that just exposing the name is sufficient. See our soulution, to the left, compared with OSM CyclOSM layer to the right. 
![bilde](https://user-images.githubusercontent.com/70061303/227134878-81128bca-01f6-4242-80a5-fb7a2f86d257.png)

**Comment by tsobuskerudbyen** [comment]
Concerning documentation: It was well described in https://github.com/buskerudbyen/proposal-visualizer/pull/4, so I added it to my training document. This makes it easier to get the people doing updates to the OSM map to tag things correctly. So, no further actions are needed on your side.
