### ISSUE TITLE
Improve UX on small screens 

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#21]
Still issues on small screens:

1. The GPS location button seems to be really slow. (Is it only my old Android mobile? Can you please check, and I will do the same on other mobile devices back home.)
2. The legend, when minimized, is just an empty square. Can it be replaced with e.g. three horizonal lines button? (Relevant for all screen sizes this.)
3. No attribution visible on mobile devices. Screenshot from Firefox. Same issue on Chrome as well.
4. Zoom buttons and snap to North/South layout button is not fully visible. Checked on Chrome, same issue there.

![bilde](https://user-images.githubusercontent.com/70061303/224658797-c8453af0-2870-4c9f-9e0b-23503c1fc812.png)

**Comment by Beck-berry** [comment]
(4) The bottom line disappears bacause of the mobile and desktop viewport heights are different(ly calculated). Is it ok if I use [svh](https://caniuse.com/?search=svh)? It is not supported on all devices (yet). It should work on Chrome and the newest version of Safari. 
I checked on two Android devices, it looks good but I cannot test with iOS manually. I'll go with this for now, let me know if it isn't working for you.

**Comment by Beck-berry** [comment]
For (4) I used [svh](https://caniuse.com/?search=svh) to fix the mobile viewport issue. It hopefully will work on Android and iOS devices too. (I checked on two Androids with Chrome, looked nice but could not test on Safari.) I added a fallback, so if it is not supported yet, the map will look at least better.

**Comment by Beck-berry** [comment]
About (1): 
@tsobuskerudbyen Have you tried it on other devices? Is it slow on Android only? I've read that the pace and the accuracy can depend on the momentary settings (Wi-Fi, GPS...)

[I have this issue on my device](https://stackoverflow.com/questions/72839887/mapboxgl-js-react-cant-locate-the-user-on-mobile-device) and not yet found out how I can resolve it. On PC the tracking is fast.

I do not know exactly what causes the problem. Constant user tracking was enabled, I disabled it, let's see if it's better this way.

**Comment by tsobuskerudbyen** [comment]
Bullets 1 and 2 seems to be okay. Thanks. 3 and 4 is a single issue as the UI seems to be "cropped" at the bottom of smaller screens. Same issue on newer iPad with Safari, as seen on screenshot:
![20230325_115958](https://user-images.githubusercontent.com/70061303/227713201-3d24d2d4-0f19-49db-8b88-1b3c43fb13d8.jpg)
