### ISSUE TITLE
Button "Reset bearing to north" should also reset the tilt

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#22]
If you use Ctrl + left mouse button or right mouse button you can pan and tilt the map, but there is no way of getting it back to "normal" (other than tilting it back with the same buttons). Can this function be added to the button "Reset bearing to north"?

**Comment by Beck-berry** [comment]
@tsobuskerudbyen Please close this, if works well!

**Comment by tsobuskerudbyen** [comment]
Works great! Thanks.
