### ISSUE TITLE
Visualize conditional values on highways

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#25]
When tags with conditions (e.g. opening hours or snow removal or not) are present 1) display it and 2) utilize it in routing options. Option 2 will probably need more work and be made in a feature request in OTP for bicycle routing?

Examples to handle.  Please contribute if you know of others:

1) Tunel with no lights at night:
`tunel=yes` and `bicycle!=no` and `lit!=yes`, then give information from lit to user. 
Example location: https://www.openstreetmap.org/way/34657819
`lit=Mo-Su 06:00-23:00` ➡️ Result in map: A circle icon with an i inside: Hoover information: "Tunnel med lys kun mandag til søndag kl. 06:00-23:00." (Weekdays in Norway: mandag, tirsdag, onsdag, torsdag, fredag, lørdag, søndag)
`lit=no` ➡️ "Tunnel uten lys.".
This should, for the moment not affect routing. 

2) Tunel dedicated for pedestrians and cyclists, but closed at night. (Planned opening 15th April.) 
https://www.openstreetmap.org/way/677727136
`opening_hours=Mo-Su 05:30-23:30`
Same icon as over, and similar textual information. ➡️ "Tunnel åpen mandag til søndag kl. 05:30-23:30.".

3) more complex: A tunel and elevator as part of a train station is also a huge short-cut for cyclists as the alternative route is approximately 80 meters in height difference. 
https://www.openstreetmap.org/way/460976051
`bicycle:conditional=no @ (01:00-05:00)`
Same icon as over. ➡️ "Anlegg stengt kl. 01:00-05:00.".

4) Closed road at winter. Can this only be visible during winter months? I.e. calendar from tags, or if not from November to February 
`snowplowing=no` and `highway=*`
Extreme example, but saw that there are some with an [Overpass run](https://overpass-turbo.eu/s/1viH).
https://www.openstreetmap.org/way/80561657
Same icon as over. ➡️ "Usikkert vinterføre. Anlegg er merket med at det ikke måkes om vinteren.".

**Comment by leonardehrenfried** [comment]
Visualisation on the map will not be a huge amount of work, however getting OTP to understand all of this will be.

I suggest that we have a scoping session where we talk about the various ways we could tackle this problem.

**Comment by tsobuskerudbyen** [comment]
Understood. Let us focus on part one of the ticket: "display it" in the map.

**Comment by leonardehrenfried** [comment]
Note for @Beck-berry: we never change the map itself, we just want to show an icon on the map.

**Comment by Beck-berry** [comment]
@tsobuskerudbyen Should 4 have the same icon as the others? What text should appear in the popup?

**Comment by Beck-berry** [comment]
@tsobuskerudbyen At what zoom level should the icons appear? It looks a bit weird at zoom 10, for example, when nothing else is shown but the little i-s.



![Image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/0324659e-f157-4b7b-9f25-385e86f057f1)

**Comment by tsobuskerudbyen** [comment]
Zoom level 15 is fine, as it is the same level as when the other icons are appearing (like cycle parking). Same icon on bullet 4, yes. Updated the description with text. Thanks for noticing! :)

**Comment by Beck-berry** [comment]
Thank you! Since I find it a bit trickier than the others, I created a new issue for it and will spend more time on that part.

**Comment by Beck-berry** [comment]
@tsobuskerudbyen I was wondering, won't be there any more complex data at the `lit` or `opening_hours` or any tag? These dates can be very difficult to parse and the question is, should we be able to display those? Like `Mo-Fr 12:00-18:00; We off; Sa,PH 12:00-17:00;`?
There is a pretty cool library, [opening_hours](https://www.npmjs.com/package/opening_hours), which is able to do many things. But if it is for sure, that we always will show opening hours from Monday to Sunday, I already wrote a simple parser that can do only that.
![image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/07cbd3dc-4a7b-4f72-bc70-f0b70081f823)

Or if a more complex opening_hours data comes, we could display it simply in a table. What do you think?

**Comment by tsobuskerudbyen** [comment]
Yes, please. There are all sort of days and times here, so a libray that may help us here is perfect.

**Comment by Beck-berry** [comment]
What would you think if we wrote a text with the actual today's opening hours and added a table with details? This way there would be specific info for that day and the user also could see the timetable.

![Image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/aea0b9d3-baa1-4847-8081-e6b3b3304e85)


I looked for examples via Overpass and it seems that there are not so many ways with `opening_hours` or `lit` timetables, or they are mostly the same every day, so the timetable feels a bit too much to display. So if every day is the same, we could go only with the text:


![Image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/2d59bfd0-4798-4daa-b964-ef1c74bb8eb1)


What do you think of this solution?

**Comment by tsobuskerudbyen** [comment]
Great that you can make it more compact, yes please.

**Comment by tsobuskerudbyen** [comment]
Just noticed. In the compact box there are numbers for seconds. That is not needed.
