### ISSUE TITLE
Add Privacy policy information

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#28]
As part of regulations regarding GDPR in European and Norwegian public sector, we need to add information about our Privacy policy.
We need to make this together, and maybe update it numerous times after new information and feedback. Pages we can look to and copy from:

- https://om.entur.no/personvern/ 
- https://www.drammen.kommune.no/personvern/ 

First step: Make an addition to the text: "© MapTiler © Map data from OpenStreetMap", which should read: "Personvern. © MapTiler © OpenStreetMaps bidragsytere." Personvern should then give similar popup like Hjelp, with some text in it.

Suggestion for text for now - Please look over the text under Find my location (copied from https://om.entur.no/personvern/ - There is an English version there. Under "Access"):

> **Personopplysninger og personvern**
> Buskerudbyen og Drammen kommune er ansvarlig for tjenesten som leveres her på Sykkelveier.no (og leonard.io/cycling-norway/). Se websiden [drammen.kommune.no](https://www.drammen.kommune.no/) for mer informasjon om personvern og personvernombud. Du kan også ta kontakt med oss på post @ buskerudbyen.no.
> 
> **Hvilken informasjon lagres?**
> Sykkelveier.no lagrer ingen personinformasjon om brukeren. For logger, lagres IP-adresser som besøker siden.
>
> **Videresending av informasjon**
> Alle søk på adresser eller steder i Norge blir sendt videre til Entur sitt Nasjonalt reisesøk-API. Behandling av disse dataene er dekket av [Enturs personvernregler]( https://om.entur.no/personvern/).
>
> **Hvordan sikrer vi dine personopplysninger?**
> Sykkelveier følger kravene til informasjonssikkerhet i gjeldende personvernlovgivning.
> Vi har etablert rutiner og tiltak for å sikre at uvedkommende ikke får tilgang til løsningen. Tiltakene inkluderer blant annet jevnlige risikovurderinger, tilpassede og oppdaterte tekniske systemer og fysiske prosedyrer for å ivareta informasjonssikkerheten.
>
> **Din posisjon**
> Søket med «Find my location» skjer kun i nettleseren, så posisjonen blir ikke sendt til serveren før man søker på en rute med GPS-posisjon aktiv. Posisjonen finner man ved hjelp av telefonens GPS-funksjon, WiFi-tilkoblinger, IP-adresser, RFID, Bluetooth, MAC-adresser og GSM/CDMA-celle-ID. Om nettleseren vil vite hvor man er, spør den om lov først. Du kan alltid regulere denne tilgangen i nettleserens innstillinger.
>
> Personvernerklæringen ble senest oppdatert 3. mai 2023.

**Comment by leonardehrenfried** [comment]
@tsobuskerudbyen I read the GPS section and it's correct. We can add a sentence that the GPS location is only sent to the server if a route is searched. Otherwise it's only used clientside and the server doesn't know anything about it.

And here is a section about the address search. Can you translate it?

## Address search

This website also allows you to search for addresses. This service is provided by Entur and everything you type into the address search will be sent to Entur's servers and is covered by their privacy policy.

If you don't use this feature, then no searches are sent to Entur's servers.

**Comment by tsobuskerudbyen** [comment]
Updated the Norwegian text in the ticket description. Did not add anyting on:
 
> GPS location is only sent to the server if a route is searched. Otherwise it's only used clientside and the server doesn't know anything about it.

The behviour is as soon as you click the Find my location the map is updated to the location the device is on. Hence, it must be sent to the server before a route search?!

**Comment by leonardehrenfried** [comment]
When you click on the "my location" button then nothing is sent to the server because it's not the server that displays the map. It's client-side only.

**Comment by tsobuskerudbyen** [comment]
Understood. Text updated.
