### ISSUE TITLE
Add distance information

### ISSUE THREAD

**Issue by leonardehrenfried** [buskerudbyen/cycling-norway#3]

**Comment by leonardehrenfried** [comment]
Give some basic information on how long a selected route is and elevation.

**Comment by leonardehrenfried** [comment]
@beck-berry Maybe we could introduce a panel on the left hand side which contains the from/to and the routing result.

**Comment by Beck-berry** [comment]
This is how it currently looks:

![Image](https://user-images.githubusercontent.com/46535522/229377075-27b0e778-3841-4815-82f3-89275c4e5e09.png)

It is closable with the toggle button of the search fields, and it is not visible when there are no routes planned.

@tsobuskerudbyen 
What time template would you prefer? 
What other information should we add?

@leonardehrenfried I found the `duration` and the `distance` properties of the `tripPatterns` object, but it seems to me that it does not have proper info about the elevation. Do you have any suggestions, where could I find it?

I'd be happy with any other suggestions too.

**Comment by leonardehrenfried** [comment]
@Beck-berry I will try to get this information for you from the GraphQL  API.

**Comment by leonardehrenfried** [comment]
Actually I just checked: the elevation information is not available in the API even though Entur's OTP instance has it.

I will have to speak to their developers if they are interested in adding it.

**Comment by leonardehrenfried** [comment]
For reference, here is their GraphiQL deployment: https://tinyurl.com/2ye84vea

**Comment by tsobuskerudbyen** [comment]
This looks good. Nice and stylish. :) Would love to have some elevation information as well.

**Comment by Beck-berry** [comment]
Should I create a PR for this and a new issue for the elevation, what do you think? That way the missing information doesn't stop the other two from being visible.

**Comment by leonardehrenfried** [comment]
Yes please
