### ISSUE TITLE
UX issue: No mouse pointer action to the right of from and to search boxes

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#31]
The yellow marked area in screenshot is not reacting to left or right mouse clicks. Seems to be an issue on PC computer and iPad size screens (not able to reproduce on my mobile phone). Tested in Safari, Chrome, Edge, and Firefox. Same issue in all browsers.
![bilde](https://user-images.githubusercontent.com/70061303/227571657-3f553287-d764-4d85-93b5-d6a77e1f4045.png)

**Comment by tsobuskerudbyen** [comment]
Not on live system yet. Any update here?

**Comment by Beck-berry** [comment]
It's not yet deployed, sorry. #15, #22 and this one will go together.

**Comment by leonardehrenfried** [comment]
Sorry, that one was on me. I just deployed it together with the forrest trails in the legend.

**Comment by Beck-berry** [comment]
@tsobuskerudbyen  Please close this if works well now :blush:

**Comment by tsobuskerudbyen** [comment]
Looks good. Closing.
