### ISSUE TITLE
Chrome issues: No visible icons

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#34]
See screenshot. Google Chrome has a problem with no visible icons, and they are not in Tegnforklaring either, but all lines (cycle infrastructures and routes) are okay both places. No issues in Edge or Firefox. Location from screenshot: https://leonard.io/cycling-norway/#19.71/59.7431476/10.2037986

Can it be looked into?
![bilde](https://user-images.githubusercontent.com/70061303/228542506-fd9701bb-298c-4176-91fc-5ae87707a1e3.png)

**Comment by leonardehrenfried** [comment]
I think this is because Chrome caches the response too aggressively.

I changed the cache settings last week so this won't happen in the future but I think your computer still has the old version in the cache.

Can you force a refresh with Ctrl + F5 and report back?

**Comment by tsobuskerudbyen** [comment]
1. Ctrl + F5 did not work.
2. In settings. Deleting from the last 24 hours Cookies and other site data + Cached images and files - Did not work
3. Ctrl + F5 again made all the icons appared.

**Comment by leonardehrenfried** [comment]
Has this happened again since you reported it? Or can it be closed?

**Comment by tsobuskerudbyen** [comment]
Looks good now. Closing.
