### ISSUE TITLE
Snow Ploughing: Orange status by itself not very informative in Tegnforklaring

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#44]
New text: 
> Brøyting: 3 timer eller senere

**Comment by Beck-berry** [comment]
It already has a text at the legend:

![Image](https://user-images.githubusercontent.com/46535522/236948142-ef36dfa6-1dbb-4e17-9c6e-c7b719f0d515.png)


Isn't this what you thought of?
