### ISSUE TITLE
Map design: Tunnels not visualized on primary and cycleway

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#45]
It looks like `highway=motorway` and `highway=unclassified` is visualized correctly with dotted border lines

- Example motorway: https://leonard.io/cycling-norway/#13.94/60.38124/5.29354 (https://www.openstreetmap.org/way/3252307/)
- Example unclassified: https://leonard.io/cycling-norway/#17.72/58.464375/8.768096 (https://www.openstreetmap.org/way/440069166)

But not smaller (than motorway) roads, that are more likely to be open for cyclists: 
 - `highway=primary` - Example: https://leonard.io/cycling-norway/#14.94/60.37894/5.31066 (https://www.openstreetmap.org/way/53203307 )
 - And, most importantly, `highway=cycleway` - Example: https://leonard.io/cycling-norway/#14.22/60.3489/5.30642 (https://www.openstreetmap.org/way/677727136). For the legend: "Sykkelveier i tunnel"

Can this be rectified in a similar manner to highway=motorway and highway=unclassified?

**Comment by leonardehrenfried** [comment]
@Beck-berry Bike infrastructure should use a long stroke with a short gap.
