### ISSUE TITLE
Add more POI to the map from OSM 

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#61]
Can more information be added to base map? No need to add it to the legend / "Tegnforklaring". Icons/tiles from Carto is fine, if okay to use?

- Museums: `tourism=museum` - Expose name tag if present. 
- Playgrounds: `leisure=playground` - Expose name tag if present.
- Government offices: At least `amenity=townhall`
- Tourist information: `tourism=information` and `information=office` - Expose name tag if present.
- Public toilets: `amenity=toilets` – Expose more tags if present
- Camp sites: `tourism=camp_site` and (`tents=yes` or `cabins=yes`) - Expose name tag if present.
- Public shelters: `amenity=shelter` and `shelter_type=lean_to` - Expose name tag if present.
- Beaches: `natural=beach` - Expose name tag if present.
- Drinking water: `amenity=drinking_water`
- Public libraries: `amenity=library` - Expose name tag

**Comment by Beck-berry** [comment]
@tsobuskerudbyen 
Toilets have many kind of tags (about accessability, fee, floor level, changing table availability...) - which one should we expose? Maybe we could introduce a popup that will show these details for each?

**Comment by tsobuskerudbyen** [comment]
Yes, please add a popup. All details please, yes.

Also, add a general text for this, at the bottom: "Alle toaletter kan ha åpingstider, der for eksempel bygget ellers er stengt, eller være stengt i perioder (fellesferie, vinteren, for vedlikehold, etc.)."

**Comment by tsobuskerudbyen** [comment]
Toilets: There is no library or shared code for this? For now I guess we could go with something simple, and then revisit it again if needed. So, for now: `fee`, `opening_hours` and the text over should be sufficient.

**Comment by Beck-berry** [comment]
I could not find a library, but there could be something, somewhere... For now, I added the popup as this:



![Image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/4a7c7d0b-03d7-4ff3-bc77-c39c473e9fb5)

**Comment by leonardehrenfried** [comment]
@tsobuskerudbyen Does this look ok to you?

**Comment by Beck-berry** [comment]
I updated the label.
