### ISSUE TITLE
Prioritize the visibility of best cycle parking icons where they are close together 

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#62]
Could the best parking possibilities be prioritized in the zoomed out rendering? Now it seems more random. Order: 

1. bicycle sheds
2. boxes
3. under roof
4. normal parking
5. pumps (if possible)
6. repair stations  (if possible)
7. Private parking

**Comment by Beck-berry** [comment]
1 poi-bicycle-parking-{{ type }} shed
2 poi-bicycle-parking-{{ type }} lockers
3 poi-bicycle-parking-{{ type }} covered
4 poi-bicycle-parking-public
5 poi-bicycle-pump-station
6 poi-bicycle-repair-station
7 poi-bicycle-parking-private
