### ISSUE TITLE
Pumptrack not visible on the map

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#64]
Pumptrack not visible on the map, bug or wrong tagging? See ticket #16 for feature.
For example, this one: https://www.openstreetmap.org/way/1157646246
Not visble here: https://leonard.io/cycling-norway/#17.46/60.567528/9.100898

**Comment by leonardehrenfried** [comment]
The problem is that we can deal with `sport=cycling` and `sport=bmx`, but not `sport=cycling;bmx`.

That is something that @Beck-berry can fix.
