### ISSUE TITLE
Travel time: Investigate the validity for the planned route

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#66]
Got some feedback that it seems that our solution overestimates the time used to cycle a route. Se example and comparison between Ås and Oslo under. What is the criteria and estimated time made of here?
![thumbnail_image006](https://github.com/buskerudbyen/cycling-norway/assets/70061303/3a1e8f87-2e45-4e65-b9dc-97bbda4216df)
![thumbnail_image005](https://github.com/buskerudbyen/cycling-norway/assets/70061303/0014fd45-514b-446c-82da-be1a2989704d)
https://leonard.io/cycling-norway/?from=59.66340%2C10.79422&to=59.91107%2C10.74813#9.03/59.7876/10.7977

**Comment by Beck-berry** [comment]
We use the following settings as [in this example query](https://otp2debug.entur.org/graphiql?flavor=transmodel&query=query%20TransmodelElevationQuery%20%7B%0A%20%20serverInfo%20%7B%0A%20%20%20%20version%0A%20%20%7D%0A%20%20trip(%0A%20%20%20%20modes%3A%20%7BdirectMode%3A%20bicycle%2C%20accessMode%3A%20bicycle%2C%20egressMode%3A%20bicycle%7D%0A%20%20%20%20bicycleOptimisationMethod%3A%20safe%0A%20%20%20%20triangleFactors%3A%20%7Bsafety%3A%200.6%2C%20slope%3A%200.2%2C%20time%3A%200.2%7D%0A%20%20%20%20from%3A%20%7Bcoordinates%3A%20%7Blatitude%3A%2058.89053%2C%20longitude%3A%205.71654%7D%7D%0A%20%20%20%20to%3A%20%7Bcoordinates%3A%20%7Blatitude%3A%2058.96134%2C%20longitude%3A%205.72525%7D%7D%0A%20%20)%20%7B%0A%20%20%20%20tripPatterns%20%7B%0A%20%20%20%20%20%20distance%0A%20%20%20%20%20%20legs%20%7B%0A%20%20%20%20%20%20%20%20mode%0A%20%20%20%20%20%20%20%20elevationProfile%20%7B%0A%20%20%20%20%20%20%20%20%20%20elevation%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=TransmodelElevationQuery).

```
    modes: {directMode: bicycle, accessMode: bicycle, egressMode: bicycle}
    bicycleOptimisationMethod: safe
    triangleFactors: {safety: 0.6, slope: 0.2, time: 0.2}
```

**Comment by tsobuskerudbyen** [comment]
Sorry, probably not made myself clear here. It is the time estimated to cycle a route I am questioning. Why is the time from Google Maps faster than OTP/Entur? Just checked another service – Komoot – and this estimates travel times of 2 hours and 32 minutes with a e-bike and 2:06 with road cycling. Per now I feel that our solution is estimating using longer time on longer routes, and – hence – may discourage people from cycling.

**Comment by leonardehrenfried** [comment]
@Beck-berry Can you increase the bike speed a little?

**Comment by Beck-berry** [comment]
I modified the settings like so:

```
  bicycleOptimisationMethod: triangle,
  triangleFactors: {safety: 0.5, slope: 0.2, time: 0.3}
  bikeSpeed: 7
```


![Image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/06cec613-a98e-43eb-84d6-4922da9f155a)

@tsobuskerudbyen  Is it more like what you wanted?

**Comment by tsobuskerudbyen** [comment]
For this ticket/issue there is just change in `bikeSpeed: 7`, right? I do not see any changes in the route. If that is the case, it looks good for now. Just leave it closed. Thanks!

**Comment by leonardehrenfried** [comment]
Yes, the speed should not change the route at all.
