### ISSUE TITLE
Bane NOR cyclehotel has no icon

### ISSUE THREAD

**Issue by leonardehrenfried** [buskerudbyen/cycling-norway#70]
https://leonard.io/cycling-norway/#19.7/59.7396275/10.2048885

Icon an name missing

**Comment by leonardehrenfried** [comment]
cc @tsobuskerudbyen

**Comment by leonardehrenfried** [comment]
I've fixed the immediate problem of no Bike hotel and it will be rolling out over the next two hours (depending on your cache settings).

![image](https://github.com/buskerudbyen/cycling-norway/assets/151346/b788e5b9-2213-4be2-a5b4-ab57693767ae)

However, this introduced another problem where we now have duplicate icons for private parking:

![image](https://github.com/buskerudbyen/cycling-norway/assets/151346/3b640081-5181-4a99-b03f-8bcdb974babb)

I will take care of this on Monday.

**Comment by leonardehrenfried** [comment]
@tsobuskerudbyen This should be fixed now. Can you please confirm and close the ticket if you're satisfied?

**Comment by tsobuskerudbyen** [comment]
Looks good. Thanks. Closing.

**Comment by tsobuskerudbyen** [comment]
No close button here for me. Can you please close?
