### ISSUE TITLE
Improvements on the prototype to use as an embeded webpage

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#71]
Scenario: Kolumbus would like to try out a cycling campaign by using the prototype web page into an existing website under their control. Can this be done?

We need some improvements on the existing solution to make this work better. Currently the start location is Drammen. There is only one way, from my tests, to change this.
1. Can a partial URL work in the same way as writing in an selecting a location in the Fra/from field? So that for example https://leonard.io/cycling-norway/?from=58.97425%2C5.73141 will work. See test results under.
1. By default the location icon is disabled when the page is embedded. Can it be removed?
1. Would it be possible to select some of the elements from "Tegnforklaring" turned off by URL? For example, if a location is cluttered with info turn off shops and "Sykkelskap".

Testing done with: https://www.w3schools.com/TAGS/tryit.asp?filename=tryhtml5_embed_html

- Adding `scr="https://leonard.io/cycling-norway/"` works, but only shows Drammen.
- Adding `scr="https://leonard.io/cycling-norway/#14/58.96657/5.73262"` works, but shows no from location icon.
- Adding `scr="https://leonard.io/cycling-norway/?from=58.97425%2C5.73141"` it does not change the location of the underlying map
- Adding `scr="https://leonard.io/cycling-norway/?from=58.97425%2C5.73141&to=58.96657%2C5.73262#15.08/58.97043/5.73167"` does not show anything

Is this a special character thing?

**Comment by leonardehrenfried** [comment]
Add option to to add a label in the "from" field.

**Comment by Beck-berry** [comment]
Number 3 is already solved via #58. 

Tried with `https://leonard.io/cycling-norway/?layers=bicycle-route-national-overlay%2Cbicycle-route-local-overlay%2Cpoi-bicycle-parking-public%2Cpoi-bicycle-parking-private%2Cpoi-bicycle-parking-lockers%2Cpoi-bicycle-parking-shed%2Cpoi-bicycle-parking-covered%2Cpoi-bicycle-repair-station%2Cpoi-snow-plow-ok%2Cpoi-snow-plow-warn%2Cpoi-snow-plow-snow%2Cpoi-bicycle-pump-station%2Cpoi-bicycle-shop%2Cpoi-pump-track%2Cbicycle-route-national-background#14/59.739/10.1878` and only "Nasjonale sykkelruter" was visible on the embed map. You can move the map, and the new appearings will be *enabled* by default.
