### ISSUE TITLE
Minor cycle infrastructure issue: cycleway:*=separate marked as infrastructure

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#72]
Just spotted this (Havnegata) road: https://leonard.io/cycling-norway/#20.13/59.7275316/10.248521. It is marked with cycle infrastructure, but there is nothing like this on this road. Seems to be because of the tag: `cycleway:*=separate`. See: https://www.openstreetmap.org/way/946847896/history#map=21/59.72754/10.24848
Not sure how it shows up, maybe from StreetComplete, but it is present many places. See: https://overpass-turbo.eu/s/1zzr. Can this be fixed? As in removed from the "Sykkelveier" green line category.

**Comment by leonardehrenfried** [comment]
Tags that are not cycle infrastructure:

- `cycleway:right=separate`
- `cycleway:left=separate`
- `cycleway=separate`

@Beck-berry Please exclude from the map.
