### ISSUE TITLE
Translate the hoover text information

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#77]
- Find my location -> "Finn min posisjon"
- Zoom in -> "Zoom inn"
- Zoom out -> "Zoom ut"
- Reset bearing to north -> "Roter nord opp og sett kartet flatt"
- - -
- Location not available -> "Posisjon ikke tilgengelig"
- Use ctrl + scroll to zoom the map -> "Bruk Ctrl + rull for zoom"
- Use ⌘ + scroll to zoom the map -> "Bruk ⌘ + rull for zoom"
- Use two fingers to move the map -> "Bruk to fingre for å bevege kartet"
- Enter fullscreen -> "Fullskjerm"
- Exit fullscreen -> "Avslutt fullskjerm"

**Comment by Beck-berry** [comment]
@tsobuskerudbyen There are other labels, we could you a translation for:
* Location not available
* Use ctrl + scroll to zoom the map
* Use ⌘ + scroll to zoom the map
* Use two fingers to move the map
* Enter fullscreen
* Exit fullscreen

Thank you!

**Comment by tsobuskerudbyen** [comment]
Updated the ticket description now. Also found a spelling mistake in the first one. 

Do you then know when the latter info is used? It is not visible on https://kongsberg.kommune.no/nyhet/ac4cf0ad-1bc7-4847-97c9-b7c809ba25ae, with the embed HTML tag now. When?

**Comment by Beck-berry** [comment]
For the fullscreen option, we can add a button like this: https://docs.mapbox.com/mapbox-gl-js/example/fullscreen/
Do we need it?

I asked you to translate all the labels that can be used, but we do not use all of them. (eg. FullscreenControl)
