### ISSUE TITLE
Map starting point: Based on location by default – Then random big cites in Norway?

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#79]
When moving the site to new URL is it possible to change the start location of the map. Default the location on the device, if shared with the webpage. Then, if no location is available, show a random bigger city center in Norway (zoom level down to detail). Do I need to make a list, or can this be automated in some way?

If this is a lot of work, just make it zoom out around `#8/59.868/10.322`.

**Comment by leonardehrenfried** [comment]
If we defined a list of big cities (not hard) then this can be easily randomised and automated.
