### ISSUE TITLE
Turning off "Sykkelskap" in "Tegnforklaring"/legend does not remove the Bikely API data

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#83]
I think this was working previously.
![bilde](https://github.com/buskerudbyen/cycling-norway/assets/70061303/ff909351-8985-4eeb-afe3-b86d9e0e9454)

**Comment by Beck-berry** [comment]
The `Sykkelskap` switcher stands for the `bicycle-parking-lockers` POI, not the `bikely` POI. [See example here](https://leonard.io/cycling-norway/?layers=bicycle-lane%2Cbicycle-route-national-background%2Cbicycle-route-local-background%2Cbicycle-route-national-overlay%2Cbicycle-route-local-overlay%2Cpoi-bicycle-parking-public%2Cpoi-bicycle-parking-private%2Cpoi-bicycle-parking-lockers%2Cpoi-bicycle-parking-shed%2Cpoi-bicycle-parking-covered%2Cpoi-bicycle-repair-station%2Cpoi-snow-plow-ok%2Cpoi-snow-plow-warn%2Cpoi-snow-plow-snow%2Cpoi-bicycle-pump-station%2Cpoi-bicycle-shop%2Cpoi-pump-track%2Cpoi-bike-track&from=59.74328%2C10.20370#17.9/59.743253/10.20311). Bikely is not switchable (yet?).

**Comment by tsobuskerudbyen** [comment]
Please include Bikely in the Sykkelskap toggle function.

**Comment by Beck-berry** [comment]
As I can see now, there cannot be two layers behind the same toggle function. We can either introduce another switch for the bikely POI (in this case, we need a label) or totally recreate the legend functionality.

**Comment by tsobuskerudbyen** [comment]
Right. No need to recreate the legend. Just add a switch and call it "Bikely parkering".
