### ISSUE TITLE
Roadworks – tagged in OSM – visible on the map

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#84]
As a way to improve both the standard solution and any embedded maps in news on web scenarios, we should be able to show roads that are closed. To the be able to inform cyclists and route them around. Icon: No entry sign. (See mockup under.)

Need help on this, but my suggestion: 

1. construction=* and highway=construction and (construction<>motorway or bicycle=no) - Tested here: http://overpass-turbo.eu/s/1AG0
2. check_date=[has a date] – To avoid cases that are old and not correctly updated?

We avoid construction areas. This is too complex in my book. Correct me if I am wrong. 

![266586943-8ee4c23c-d472-4a07-9e2c-fd525b20f3d7](https://github.com/buskerudbyen/cycling-norway/assets/70061303/9dece46b-e6b5-40be-960b-8a850f379958)

**Comment by leonardehrenfried** [comment]
This is not a huge amount of work. OTP already excludes construction sites from routing. Now what we need is a map visualization.

**Comment by tsobuskerudbyen** [comment]
Great. It may be, at a later stage, room for looking into more complex development also:

1. Harvesting data from official data sharing for roadworks: https://git.vegvesen.no/projects/DATEX2/repos/datex2-spesifications/browse/3.1
1. Is it possible to automatically remove roadworks after a certain date? By tags described above.

Please comment on this and move any further development task and text out to a new ticket/issue.

**Comment by Beck-berry** [comment]
> Is it possible to automatically remove roadworks after a certain date?

@tsobuskerudbyen, do you mean not to show the sign anymore if the `check_date` was long ago? Yes, we can do that, but you have to define "long ago" for this.

**Comment by tsobuskerudbyen** [comment]
Slightly relevant: I see that [StreetComplete](https://wiki.openstreetmap.org/wiki/StreetComplete/Quests) asks "Is this path completed?" after 4 weeks, so that is good.

So, thinking a bit more about this: This function can be extended to all sort of levels. Currently, with no bigger plans for data import and special requests from some of our partners, we can leave this as simple as possible for now. Therefore, no need to add checks for `check_date` for now. Prioritize to beautify the blocked roads, in: https://github.com/buskerudbyen/proposal-visualizer/pull/19

Reason: What would we have done with the check? We could have 
1. opened the road automatically, or 
2. informed the user that this is "old" roadworks, but OTP would still route around it, or 
3. we could ask the user to check and make a OSM note of the result.
4. ...other options. 

I.e. all sorts of UX possibilities here.

**Comment by tsobuskerudbyen** [comment]
Possible to deploy this now?

**Comment by leonardehrenfried** [comment]
I've deployed it now and I will roll out throughout the evening and tomorrow (since there are several chache layers).
