### ISSUE TITLE
Change the favicon and title/bookmark text for sykkelveier.no

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#85]
Change: `<title>Cycling Norway Routing Prototype</title>` to: "Sykkelveier.no – Finn din neste sykkelrute"

Change: `<meta name="description" content="Web site created using create-react-app"/>` - to: "Sykkelkart og -ruteplanlegger for Norge"

Icon suggestion attached. May need som cropping.
<img width="312" alt="Sykkeldame" src="https://github.com/buskerudbyen/cycling-norway/assets/70061303/4b9e8a63-8c41-4826-96ff-dfa9b89500df">

**Comment by leonardehrenfried** [comment]
I've updated the title and meta and added the favicon. The problem is that it's too detailed so we need something simpler. Also we need a version without a white background. 

Can you provide these things?

**Comment by tsobuskerudbyen** [comment]
I think it looks rather good now. Checked in Safari on iPad, Edge on Win, and in Firefox it also looks good. Except in the bookmark row. See screenshot. Any clue to fix this?

Also, why do you @leonardehrenfried think it is needed with something simpler? And same with the transparent background?  

![bilde](https://github.com/buskerudbyen/cycling-norway/assets/70061303/5a48ca1c-4aa9-4025-84b4-31d5280c7430)

**Comment by leonardehrenfried** [comment]
For a freshly made bookmark it looks like this for me:

![Screenshot from 2023-10-30 11-18-19](https://github.com/buskerudbyen/cycling-norway/assets/151346/5bb90d4f-dee6-4f7d-9add-6c5a6eeca8ee)

My theory is that Firefox caches these icons. Can you create a new one and see what it looks like?

**Comment by Beck-berry** [comment]
@tsobuskerudbyen Can this be closed?

**Comment by tsobuskerudbyen** [comment]
Yes. I can do that now.
