### ISSUE TITLE
Marked one-way roads that can be cycled both ways with a green arrow the cycling-only way

### ISSUE THREAD

**Issue by tsobuskerudbyen** [buskerudbyen/cycling-norway#99]
One-way roads that are tagged with the possibility to cycle both should be marked better - `oneway=yes` and `oneway:bicycle=no`. If the route is recommended on these roads now it looks like it is a mistake. Should be no conflicts with locations where there are cycle paths one or both directions.

The Cycle Map standard layer in OSM has a good solution to this:
https://www.openstreetmap.org/relation/10483726#map=18/59.74472/10.20154&layers=C
![image](https://github.com/buskerudbyen/cycling-norway/assets/70061303/54c21ec3-6d33-45e8-bc80-ac70741b0625)
Our solution:
https://sykkelveier.no/#18.4/59.744885/10.201917
![image](https://github.com/buskerudbyen/cycling-norway/assets/70061303/6f56de6d-d5bc-487b-a5ed-8af9deb3098c)
This road: https://www.openstreetmap.org/way/8198236

**Comment by leonardehrenfried** [comment]
We could change the arrow to be only applicable for bicycles or we could come up with a more complex visualisation. Which one do you prefer, @tsobuskerudbyen ?

**Comment by tsobuskerudbyen** [comment]
I prefer to make the arrow as close to what the Cycle Map standard layer in OSM have, please. Then a cyclist will be abel to see that it is a one way street for motor traffic.

**Comment by Beck-berry** [comment]
It will look like this:

![Image](https://github.com/buskerudbyen/cycling-norway/assets/46535522/120ef547-be5f-4063-80c7-236fb3d4ebfc)

**Comment by tsobuskerudbyen** [comment]
Great. One thing: Can the green colour be the same as cycle infrastructure in the map in general (top right in the screenshot you just made).

**Comment by tsobuskerudbyen** [comment]
Possible to fix and deploy this one before a presentation tomorrow? (I have fixed a lot of one way streets in Gjøvik.)

**Comment by tsobuskerudbyen** [comment]
No worries. I can show it in OSM.

**Comment by leonardehrenfried** [comment]
Short update: @Beck-berry _is_ available and has pushed the fix, however it will take around 4 hours to compute the entirety of Norway. So, depending when exactly your meeting is, you might see it already or might not. :crossed_fingers:
